version: '3.8'

services:
  # 1. The Redis Cache (For Rate Limiting)
  redis:
    image: redis:alpine
    container_name: cooperative_redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  # 2. Your FastAPI Backend
  backend:
    image: alains04/coop-backend:latest
    container_name: cooperative_backend
    ports:
      - "8000:80"
    env_file:
      - .env  # Pointing directly to the .env file on the server
    environment:
      - REDIS_URL=redis://redis:6379/0
    volumes:
      - ./coop_db:/backend/data
    depends_on:
      - redis
    restart: unless-stopped

  # 3. Your React/Vite Frontend
  frontend:
    image: alains04/coop-frontend:latest
    container_name: cooperative_frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped