"""fully functional crud

Revision ID: ee0d7a9349f8
Revises: 8938cbac7b52
Create Date: 2026-02-25 12:05:32.674302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ee0d7a9349f8'
down_revision: Union[str, Sequence[str], None] = '8938cbac7b52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('loan', 'payable_at')
    op.add_column('payments', sa.Column('late_fee_amount', sa.Numeric(precision=12, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'late_fee_amount')
    op.add_column('loan', sa.Column('payable_at', sa.DATE(), nullable=False))
    # ### end Alembic commands ###
